name: Build and Release Mainnet

on:
  workflow_dispatch:

jobs:
  deploy_image:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to docker hub
      run: docker login -u atletanetwork -p ${{ secrets.REGISTRYPASS }} docker.io
      
    - name: Set timestamp variables
      run: |
          TIMESTAMP=$(date +%d%m%y-%H%M%S)
          echo "TIMESTAMP: $TIMESTAMP"

    - name: Build and push docker image
      run: |
          docker build --build-arg BUILD_FEATURES=mainnet-runtime --tag docker.io/atletanetwork/atleta-node:mainnet-${TIMESTAMP} .
          docker tag docker.io/atletanetwork/atleta-node:mainnet-${TIMESTAMP} docker.io/atletanetwork/atleta-node:mainnet-latest
          docker push docker.io/atletanetwork/atleta-node:mainnet-${TIMESTAMP}
          docker push docker.io/atletanetwork/atleta-node:mainnet-latest
